In [1]:
Lista =[5,6,7,53]

def num_primo():
    for item in Lista:
        if item%item==0 and item%1==0 and item%2!=0 and item > 2:
            print("ES PRIMO")
        else:
            print("NO_ES_PRIMO")

In [2]:
num_primo()

ES PRIMO
NO_ES_PRIMO
ES PRIMO
ES PRIMO


In [786]:
"""Script creado por @rikardoroa"""
"""Juego de la vida Version 1.0"""

import emoji
import numpy as np

def creacion_sub_arreglos_juego_vida():
    #este juego consiste en mover tantas posiciones a la izquierda donde se encuentra el uno
    print("I love Learning Python" , emoji.emojize("\U0001F970, \U0001F40D, \U0001F60E, \U0001F600, \U0001F60F, \U0001f4bb", use_aliases=True)+"\n")
    #declaracion de numpy arrays
    a = np.array([1,0,0])
    b = np.array([0,1,1])
    c = np.array([1,1,0])
    z= np.array([])
    z1= np.array([])
    r= np.array([])
    k = np.array([])
    t = np.array([])
    s = np.array([])
    #recorriendo y validando arrays a,b,c y anexandolos al array z
    for i in range(len(a)):
        for col in range(a.shape[0]):
            for item in a:
                if  a[i] == 1:
                    a[:i+1]= 0
                elif a[i] == 0:
                    a[:i]= 1
    for i in range(len(a)):
        for col in range(a.shape[0]):
            for item in a:
                if  a[i] == 1:
                    a[:i]= 0
    for item in a:
        z = np.append(z,item)
    for i in range(len(b)):
        for col in range(b.shape[0]):
            for item in b:
                if  b[i] == 1:
                    b[:i]= 0
    for b_item in b:
         z = np.append(z,b_item)
    for i in range(len(c)):
        for col in range(c.shape[0]):
            for item in c:
                if  c[i] == 0:
                    c[:i+1]= 1
    for c_item in c:
         z = np.append(z,c_item)
    z = z.reshape((3, 3))
    z= np.round(z.astype(int))
    
    #aqui empieza la segunda validacion donde se toma el array z como nuevo inicio y se subdivide
    #para crear el array z1
    for i in range(len(z)):
        for fila in range(len(z)):
            if i <len(z):
                r = np.append(z, z[i:fila])
                r = np.split(z,len(z))
                r = np.array(r)
    for col in range(r.shape[0]):
            if col == 0:
                k=np.append(k,r[col]).astype(int)
                for i in range(len(k)):
                    for col in range(k.shape[0]):
                        for item in k:
                            if  k[i] == 0:
                                k[:i] = 0
                for item in k:
                    z1 = np.append(z1,item).astype(int)
            elif col == 1:
                t = np.append(t,r[col]).astype(int)
                for i in range(len(t)):
                    for col in range(t.shape[0]):
                        for item in t:
                            if  t[i] == 0:
                                t[:i] = 1 
                for item in t:
                    z1= np.append(z1,item).astype(int)
            elif col == 2:
                s= np.append(s,r[col]).astype(int)
                for i in range(len(s)):
                    for col in range(s.shape[0]):
                        for item in s:
                            if  s[i] == 1:
                                aux = s[i]
                                aux2 = 0
                                s[i] = aux2
                                s[:i] = aux
                                s = s[::-1]
                for item in s:
                    z1 = np.append(z1,item).astype(int)
    z1 = z1.reshape((3, 3))
    #Se imprime en Pantalla la salida de los dos arrays(arreglos)
    print(z,":Salida Uno")
    print(z1,":Salida dos")



            



           
            
        


            
         
            
        

In [787]:
creacion_sub_arreglos_juego_vida()

I love Learning Python 🥰, 🐍, 😎, 😀, 😏, 💻

[[0 1 0]
 [0 0 1]
 [1 1 1]] :Salida Uno
[[0 0 0]
 [1 0 1]
 [0 1 1]] :Salida dos
